name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: npm install wrangler@latest

    - name: Build project
      run: npx wrangler deploy --dry-run --outdir=dist

    - name: Copy and modify files
      run: |
        cp dist/worker.js dist/worker-original.js
        echo -e "/*!\\n  * v2ray Subscription Worker (${GITHUB_SHA})\\n  * Copyright 2024 Vahid Farid (https://twitter.com/vahidfarid)\\n  * Licensed under GPLv3 (https://github.com/vfarid/v2ray-worker/blob/main/Licence.md)\\n  */\\n\\n$(cat dist/worker.js)" > dist/worker.js

    - name: Deploy to Cloudflare
      run: |
        sed -i "s/KV_NAME/${{ secrets.KV_NAME }}/g" wrangler.toml
        npx wrangler deploy --api-token ${{ secrets.CLOUDFLARE_API_TOKEN }} --account-id ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
